### ISSUE TITLE
Finish User Authentication

### ISSUE THREAD

**Issue by Joseph-Kung** [Joseph-Kung/Yurbnb#3]
Hello Ronil,

I just finished user authentication. Here is the link to the live demo https://yurbnb.herokuapp.com/#/.

**Comment by ronilbhatia** [comment]
# User Auth

## Functionality

- [ ] The main button with logo should link to `/`
- [ ] Has working demo login

### Before Login

- [ ] The `/login` page should not display a link to `Log In`. Same for `/signup`
- [ ] Going to a random route `/#/oweiniouewbrviuwebv` should redirect or display a 404 page
- [ ] Errors should display for both `/signup` and `/login`.
- [ ] Errors should clear when moving between `/signup` and `/login`.
- [ ] Can sign up a user
- [ ] Can sign in as a user
- [ ] Can log out a user
- [ ] Can't sign up with the same username/email
- [ ] Pressing enter after filling out the session form should use the form data, not the demo user

### After Login

- [ ] Should not be able to visit `/login` or `/signup`
- [ ] Should be able to refresh the page and still be logged in

## Style

- [ ] The site should look exactly like the actual site
- [ ] All relevant elements should have `cursor: pointer` on hover
- [ ] When errors are displayed, most elements should not move around the page (particularly input boxes)
- [ ] Remove Redux logger and all console.log()'s from production

**Comment by ronilbhatia** [comment]
Hey Joseph,

Great job in putting this together - it looks great! I'm gonna be a little nitpicky on some of the styling, but all the core parts are there.

1) Right now your session form has a "Submit" button, but on the real AirBnB website it says either "Sign Up" or "Log In" depending on which form it is.
2) They have a nice line separating the Login button from the "Don't have an account? Sign Up" part. I would add this in, and also add some more padding to the bottom and top of your modal as it seems a bit crammed right now.
![screen shot 2018-12-13 at 11 31 44 am](https://user-images.githubusercontent.com/32026924/49962845-3bce6b80-fecb-11e8-8704-cf251f3a14e7.png)
![screen shot 2018-12-13 at 11 31 52 am](https://user-images.githubusercontent.com/32026924/49962846-3c670200-fecb-11e8-81f5-addfcef6b330.png)

3) Your logo in your nav bar is a pretty big compared to the real site, I would make this maybe half of its current size.
4) The microscope in your search bar is very close to the left edge, I would push it more into the search bar.
![screen shot 2018-12-13 at 11 45 53 am](https://user-images.githubusercontent.com/32026924/49963414-c368aa00-fecc-11e8-8a7b-48cd5eb943fd.png)
![screen shot 2018-12-13 at 11 45 59 am](https://user-images.githubusercontent.com/32026924/49963415-c368aa00-fecc-11e8-9dff-71e8e486e088.png)

5) Temporarily remove your logger, commit, and push to Heroku so that your logger does not show up in production.

**Comment by ronilbhatia** [comment]
Great job addressing all my comments! I'm closing this issue - can you delete the previous one you had made for User Auth, and just rename this one as you had named that one and add the `core feature` label?
